# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8f35fedfbcf1535d2f06741bf6b7c69e66fa0e2fb48d5d6872b1f6717122ecafd0811261df1c7d06a4fb021443ba5b1bb9175f3656f93b91fc4ace5f42bd071

test:
  secret_key_base: 3e0092d9db84f58b79b8c68e4c5f39492fad8424111a5685a9dca13f3258f377928ad3de31ecb0a9f854f28a11aab3aff88b3f67f4aa00c8e6e09b99124d2401

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
